const express = require('express');
const { UserController } = require('../../controllers');
const { UserMiddleware } = require('../../middlewares');
const userMiddleware = require('../../middlewares/user-middleware');
const router = express.Router();
router.get('/isAuthenticatedUser', UserController.isAuthenticated);
router.get('/', UserController.getAllUsers);
router.post('/register', userMiddleware.validateRegisterUser, UserController.createUser);
router.post('/signIn', UserMiddleware.validateRegisterUser, UserController.signIn);
router.get('/:userId', UserController.getUserById);
router.delete('/:userId', UserController.deleteUser);
module.exports = router;
